name: docker-react CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag kkazlou/docker-react

    - name: Run tests
      run: docker run -e CI=true kkazlou/docker-react npm test
